# Generated by Django 5.0.4 on 2024-06-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rekapulasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=255)),
                ('unit_kerja', models.CharField(max_length=255)),
                ('id_regu', models.IntegerField()),
                ('terlambat', models.IntegerField(default=0)),
                ('pulang_cepat', models.IntegerField(default=0)),
                ('terlambat_menit', models.IntegerField(default=0)),
                ('pulang_cepat_menit', models.IntegerField(default=0)),
                ('tanpa_keterangan', models.IntegerField(default=0)),
                ('terlambat_izin', models.IntegerField(default=0)),
                ('pulang_cepat_izin', models.IntegerField(default=0)),
                ('lupa_absen_masuk', models.IntegerField(default=0)),
                ('lupa_absen_pulang', models.IntegerField(default=0)),
                ('full', models.IntegerField(default=0)),
                ('half', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'rekapulasi',
            },
        ),
    ]
