# Generated by Django 5.0.4 on 2024-06-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('pertanyaan1', models.TextField()),
                ('pertanyaan2', models.TextField()),
            ],
            options={
                'db_table': 'survey',
            },
        ),
    ]
