# Generated by Django 5.0.4 on 2024-06-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('point_regu', models.IntegerField()),
            ],
            options={
                'db_table': 'survey',
            },
        ),
    ]
