# Generated by Django 5.0.4 on 2024-06-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_absen', models.FloatField()),
                ('nilai_jurnal', models.FloatField()),
                ('nilai_kuisioner', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('regu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.regu')),
            ],
        ),
        migrations.CreateModel(
            name='JurnalHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('tanggal', models.DateField()),
                ('skp_tahunan', models.CharField(max_length=100)),
                ('jurnal_harian', models.TextField()),
                ('jumlah', models.IntegerField()),
                ('satuan', models.CharField(max_length=50)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('nilai', models.FloatField()),
                ('komentar', models.TextField()),
                ('tanggal_isi', models.DateField()),
                ('lampiran', models.CharField(blank=True, max_length=100, null=True)),
                ('regu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.regu')),
            ],
        ),
        migrations.CreateModel(
            name='HasilPrediksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_status', models.CharField(max_length=50)),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('penilaian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.penilaian')),
                ('regu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.regu')),
            ],
        ),
        migrations.CreateModel(
            name='Rekapitulasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('unit_kerja', models.CharField(max_length=255)),
                ('terlambat', models.IntegerField()),
                ('pulang_cepat', models.IntegerField()),
                ('terlambat_menit', models.IntegerField()),
                ('pulang_cepat_menit', models.IntegerField()),
                ('tanpa_keterangan', models.IntegerField()),
                ('terlambat_izin', models.IntegerField()),
                ('pulang_cepat_izin', models.IntegerField()),
                ('lupa_absen_masuk', models.IntegerField()),
                ('lupa_absen_pulang', models.IntegerField()),
                ('full', models.IntegerField()),
                ('half', models.IntegerField()),
                ('total', models.IntegerField()),
                ('regu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.regu')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_regu', models.IntegerField()),
                ('regu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.regu')),
            ],
        ),
    ]
